project_id = "lbzgkpxyyrvsrzfvgjnb"

[api]
enabled = true
port = 54321
schemas = ["public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "exp://localhost:8081"
additional_redirect_urls = ["share2family://"]
jwt_expiry = 3600
enable_signup = true
enable_anonymous_sign_ins = true

[auth.external.apple]
enabled = true
client_id = ""
secret = ""

[auth.external.google]
enabled = true
client_id = ""
secret = ""

[db]
port = 54322

[studio]
enabled = true
port = 54323

[storage]
enabled = false

[realtime]
enabled = true
